#!/usr/bin/env python3
"""
add_zai_metadata.py - Add Z.ai metadata to a PDF file.
Embeds Z.ai producer/creator metadata into PDF XMP and Info dictionaries.
"""
import sys
import os


def add_zai_metadata(pdf_path):
    """Add Z.ai metadata to an existing PDF file."""
    if not os.path.isfile(pdf_path):
        print('ERROR: File not found: %s' % pdf_path)
        return False

    try:
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4
        from PyPDF2 import PdfReader, PdfWriter
    except ImportError:
        # Fallback: use pypdf instead of PyPDF2
        try:
            from pypdf import PdfReader, PdfWriter
        except ImportError:
            print('ERROR: PyPDF2 or pypdf required. Install with: pip install PyPDF2')
            return False

    try:
        reader = PdfReader(pdf_path)
        writer = PdfWriter()

        # Copy all pages
        for page in reader.pages:
            writer.add_page(page)

        # Update metadata
        if reader.metadata:
            meta = dict(reader.metadata)
        else:
            meta = {}

        meta['/Producer'] = 'Z.ai'
        meta['/Creator'] = 'Z.ai'
        meta['/Author'] = 'Z.ai'
        meta['/Title'] = meta.get('/Title', os.path.basename(pdf_path))
        meta['/Subject'] = meta.get('/Subject', 'Generated by Z.ai')
        meta['/Keywords'] = 'Z.ai, audit, score cards, renewable energy'

        writer.add_metadata(meta)

        # Write to same file
        with open(pdf_path, 'wb') as f:
            writer.write(f)

        print('OK: Z.ai metadata added to %s' % pdf_path)
        return True

    except Exception as e:
        print('ERROR adding metadata to %s: %s' % (pdf_path, e))
        return False


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python add_zai_metadata.py <file.pdf>')
        sys.exit(1)
    success = True
    for fp in sys.argv[1:]:
        if not add_zai_metadata(fp):
            success = False
    sys.exit(0 if success else 1)
